name: Publish Docker Image

on:
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # This condition ensures the job only runs if the triggering workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Checkout the specific commit that triggered the 'Create Release' workflow
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Get short commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: petre/java-example:latest,petre/java-example:${{ steps.vars.outputs.sha_short }}