name: Create Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      # This permission is required to create a release
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build gradle wrapper
        run: gradle wrapper

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test

      - name: Build distribution artifact
        run: ./gradlew distZip

      - name: Create Release and Upload Artifact
        uses: softprops/action-gh-release@v2
        with:
          # The name of the tag will be the short commit SHA
          tag_name: ${{ github.sha }}
          # The files to upload as release assets
          files: build/distributions/java-example.zip